name: dd_blog_macos
description: liandiandian blog macos version v1
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  riverpod: ^1.0.3
  markdown: ^5.0.0
  flutter_widget_from_html_core: ^0.8.5+1
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3
  flutter_markdown: ^0.6.10
  hive_flutter: ^1.1.0
  hive: ^2.1.0
  waterfall_flow: ^3.0.2
  flutter_easyrefresh: ^2.2.1
  dd_check_plugin: any
  macos_ui: ^0.12.4+3
  dataoke_sdk:
    path: ../../../ldd/plugins/dataoke_sdk

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

